### ISSUE TITLE
Module version mismatch. Expected 43, got 48.

### ISSUE THREAD

**Issue by ua2004** [iceddev/bcrypt-as-promised#4]
I have the following:

```
Node: 6.1.0
NPM: 3.8.1
Node-webkit: 0.12.3
Windows 7 x64
Visual Studio 2013
```

Here is my `authenticate` method:

``` javascript
    authenticate: function(login, password) {
            var bcrypt = require('bcrypt-as-promised');
            return User.findOne({where: {
               login: login,
            }}).then(function(user) {
               if(user === null) return false;
               return bcrypt.compare(password, user.password)
               .then(function() {
                  return true; // password matches
               })
               .catch(function() {
                  return false; // invalid password
               });
            });
         },
```

Console tests are working fine but whenever I run node-webkit I get this error:

```
message: "Module version mismatch. Expected 43, got 48."
stack: "Error: Module version mismatch. Expected 43, got 48.
at Error (native)
at Module.load (module.js:346:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:356:17)
at require (module.js:375:17)
at bindings (D:\Node\Project S\node_modules\bindings\bindings.js:76:44)
at Object.<anonymous> (D:\Node\Project S\node_modules\bcrypt\bcrypt.js:3:35)
at Module._compile (module.js:451:26
at Object.Module._extensions..js (module.js:469:10)
at Module.load (module.js:346:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:356:17)
at require (module.js:375:17)
at Object.<anonymous> (D:\Node\Project S\node_modules\bcrypt-as-promised\index.js:5:14)
at Module._compile (module.js:451:26)
at Object.Module._extensions..js (module.js:469:10)"
```

I tried to rebuild and recompile `bcrypt` module separately but no luck.

**Comment by riazXrazor** [comment]
i'm also facing same issue :(

**Comment by monteslu** [comment]
good news!  the bcyrpt library that this library uses supports promises directly:
https://github.com/kelektiv/node.bcrypt.js#with-promises


this library is obsolete :)
